### ISSUE TITLE
Error when training 64-pixel images by SMPLGait model

### ISSUE THREAD

**Issue by zhang123-sys** [Gait3D/Gait3D-Benchmark#15]
`
CUDA_VISIBLE_DEVICES=0 python -m torch.distributed.launch --nproc_per_node=1 lib/main.py --cfgs ./config/smplgait_64pixel.yaml --phase train
`

**Comment by zhang123-sys** [comment]
```
Traceback (most recent call last):
File "lib/main.py", line 69, in
run_model(cfgs, training)
File "lib/main.py", line 44, in run_model
model = Model(cfgs, training)
File "/hy-nas/Gait3D-Benchmark-main/lib/modeling/models/smplgait.py", line 19, in init
super().init(cfgs, is_training)
File "/hy-nas/Gait3D-Benchmark-main/lib/modeling/base_model.py", line 166, in init
self.optimizer = self.get_optimizer(self.cfgs['optimizer_cfg'])
File "/hy-nas/Gait3D-Benchmark-main/lib/modeling/base_model.py", line 237, in get_optimizer
valid_arg = get_valid_args(optimizer, optimizer_cfg, ['solver'])
File "/hy-nas/Gait3D-Benchmark-main/lib/utils/common.py", line 48, in get_valid_args
expected_keys = inspect.getargspec(obj.init)[0]
File "/usr/local/miniconda3/envs/py37torch160/lib/python3.7/inspect.py", line 1082, in getargspec
raise ValueError("Function has keyword-only parameters or annotations"
ValueError: Function has keyword-only parameters or annotations, use getfullargspec() API which can support them
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 2490) of binary: /usr/local/miniconda3/envs/py37torch160/bin/python
Traceback (most recent call last):
File "/usr/local/miniconda3/envs/py37torch160/lib/python3.7/runpy.py", line 193, in _run_module_as_main
"main", mod_spec)
File "/usr/local/miniconda3/envs/py37torch160/lib/python3.7/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/usr/local/miniconda3/envs/py37torch160/lib/python3.7/site-packages/torch/distributed/launch.py", line 193, in
main()
File "/usr/local/miniconda3/envs/py37torch160/lib/python3.7/site-packages/torch/distributed/launch.py", line 189, in main
launch(args)
File "/usr/local/miniconda3/envs/py37torch160/lib/python3.7/site-packages/torch/distributed/launch.py", line 174, in launch
run(args)
File "/usr/local/miniconda3/envs/py37torch160/lib/python3.7/site-packages/torch/distributed/run.py", line 718, in run
)(*cmd_args)
File "/usr/local/miniconda3/envs/py37torch160/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 131, in call
return launch_agent(self._config, self._entrypoint, list(args))
File "/usr/local/miniconda3/envs/py37torch160/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 247, in launch_agent
failures=result.failures,
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
lib/main.py FAILED
Failures:
<NO_OTHER_FAILURES>
Root Cause (first observed failure):
[0]:
time : 2023-02-01_20:19:44
host : Iff0c52b8b00c015ce
rank : 0 (local_rank: 0)
exitcode : 1 (pid: 2490)
error_file: <N/A>
traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
```

**Comment by JinkaiZheng** [comment]
What version of the library package are you using? Is it consistent with the version we listed?

**Comment by zhang123-sys** [comment]
It is consistent with the version you listed.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jinkai ***@***.***&gt;; 
发送时间: 2023年2月1日(星期三) 晚上9:24
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Gait3D/Gait3D-Benchmark] Error when training 64-pixel images by SMPLGait model (Issue #15)





 
What version of the library package are you using? Is it consistent with the version we listed?

**Comment by JinkaiZheng** [comment]
This is strange, I have not met this problem, maybe you can debug at the breakpoint to see exactly why.

**Comment by zhang123-sys** [comment]
Ok, checkpoint cannot be downloaded.






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jinkai ***@***.***&gt;; 
发送时间: 2023年2月1日(星期三) 晚上9:51
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Gait3D/Gait3D-Benchmark] Error when training 64-pixel images by SMPLGait model (Issue #15)





 
This is strange, I have not met this problem, maybe you can debug at the breakpoint to see exactly why.

**Comment by JinkaiZheng** [comment]
You can use ipdb to debug, good luck :)

**Comment by qinbaigao** [comment]
> 

Hi，you can solve this problem by replacing getargspec() with getfullargspec().

**Comment by JinkaiZheng** [comment]
> > 
> 
> Hi, you can solve this problem by replacing getargspec() with getfullargspec().

@zhang123-sys Hi~ Have you solved the problem through the above suggestion?

**Comment by zhang123-sys** [comment]
Thanks, but which file has&nbsp;getargspec()?




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jinkai ***@***.***&gt;; 
发送时间: 2023年2月9日(星期四) 中午11:35
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Gait3D/Gait3D-Benchmark] Error when training 64-pixel images by SMPLGait model (Issue #15)





    
Hi, you can solve this problem by replacing getargspec() with getfullargspec().
  
@zhang123-sys Hi~ Have you solved the problem through the above suggestion?

**Comment by JinkaiZheng** [comment]
`File "/hy-nas/Gait3D-Benchmark-main/lib/utils/common.py", line 48, in get_valid_args`
`expected_keys = inspect.getargspec(obj.init)[0]`
The error location and suggestions have been indicated in the above error message. 
In addition, if you're using VSCode or PyCharm, you can use their **global search** to find everything you want in the project.

**Comment by zhang123-sys** [comment]
ok
