### ISSUE TITLE
Error when test

### ISSUE THREAD

**Issue by breeze0011** [Gait3D/Gait3D-Benchmark#16]
There was no probelm when I was training. But there is something wrong when I was testing. And I have no idea how to solve this.

**Comment by breeze0011** [comment]
Transforming:   0%|                                                                                                                                                                                            | 0/6369 [00:00<?, ?it/s]<string>:6: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
Traceback (most recent call last):
  File "lib/main.py", line 76, in <module>
    run_model(cfgs, training)
  File "lib/main.py", line 53, in run_model
    Model.run_test(model)
  File "/home/Gait3D/lib/modeling/base_model.py", line 501, in run_test
    info_dict = model.inference(rank)
  File "/home/Gait3D/lib/modeling/base_model.py", line 436, in inference
    for inputs in self.test_loader:
  File "/opt/anaconda3/envs/Gait3D/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 652, in __next__
    data = self._next_data()
  File "/opt/anaconda3/envs/Gait3D/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1347, in _next_data
    return self._process_data(data)
  File "/opt/anaconda3/envs/Gait3D/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1373, in _process_data
    data.reraise()
  File "/opt/anaconda3/envs/Gait3D/lib/python3.7/site-packages/torch/_utils.py", line 461, in reraise
    raise exception
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/opt/anaconda3/envs/Gait3D/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/anaconda3/envs/Gait3D/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    return self.collate_fn(data)
  File "/home/Gait3D/lib/data/collate_fn.py", line 121, in __call__
    fras_batch = [[my_cat(k)] for k in range(feature_num)]  # [f, g]
  File "/home/Gait3D/lib/data/collate_fn.py", line 121, in <listcomp>
    fras_batch = [[my_cat(k)] for k in range(feature_num)]  # [f, g]
  File "/home/Gait3D/lib/data/collate_fn.py", line 120, in my_cat
    [fras_batch[i][k] for i in range(batch_size)], 0)
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: could not broadcast input array from shape (72,128,88) into shape (72,)

**Comment by JinkaiZheng** [comment]
Please put up your running command and the detailed config settings, i.e., the .yaml file.

**Comment by breeze0011** [comment]
Thanks, I found the problem! I have set the plus_smpl to false. After I change it to true. Now it can run.

**Comment by JinkaiZheng** [comment]
That's good!
